remote_theme: just-the-docs/just-the-docs
nav_sort: case_insensitive

nav_external_links:
  - title: nihelp on GitHub
    url: https://github.com/magnesium2400/nihelp/tree/main
    hide_icon: false 
    opens_in_new_tab: true

aux_links:
  "magnesium2400 homepage":
    - "https://magnesium2400.github.io/"

    
